baseURL = "https://your-username.github.io/your-repo-name/"
languageCode = 'en-us'
title = 'Jayendra Sharan'
theme = 'typo'

publishDir = "docs"

[params]
  customCSS = ["css/custom.css"]

  [[params.menu]]
    name = "Home"
    url = "/"

  [[params.menu]]
    name = "About"
    url = "/about/"